[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "nordata"
author = "Nick Buker"
author-email = "nick.buker@nordstrom.net"
home-page = "https://github.com/nickbuker/nordata"
classifiers = ["License :: OSI Approved :: Apache Software License"]
